//@baseURL = http://localhost:3030
@baseURL = https://firstappwom.azurewebsites.net

@token = Bearer {{$dotenv TOKEN}}

### Se alla users

GET {{baseURL}}/users


### Skapa ny användare, TODO: fixa: crashar //63356efd00d300e9a762e206

POST {{baseURL}}/users/signup
Content-Type: application/json 

{
    "firstName" : "Sandra",
    "lastName": "Larsson",
    "email": "sandra.larsson@gmail.fi",
    "password": "Lösen1234"
}

### Logga in

POST {{baseURL}}/users/login
Content-Type: application/json 

{
    "email": "sandra.larsson@gmail.fi",
    "password": "Lösen1234"
}

### Ändra sin användare
PATCH  {{baseURL}}/users/edit/63284e765262835493f4e3ab
Authorization: {{token}}
Content-Type: application/json

{
    "email": "hanna.larsson@gmail.fi"
}


### Ta bort sin användare

DELETE {{baseURL}}/users/delete/63284e765262835493f4e3ab
Authorization: {{token}}
